/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package juegosmesa;

import java.awt.Event;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author Moise
 */
public class Cronometro extends javax.swing.JPanel {

    /**
     * Creates new form Cronometro
     */
    public Cronometro() {
        initComponents();
//        setLocation(null);
        t = new Timer(10,acciones);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelTimer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        etiquetaTitulo = new javax.swing.JLabel();
        startBtn = new javax.swing.JButton();

        PanelTimer.setBackground(new java.awt.Color(153, 204, 255));
        PanelTimer.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PanelTimer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        PanelTimer.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 16, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel2.setText("Tiempo en partida");
        PanelTimer.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 8, -1, -1));

        etiquetaTitulo.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        etiquetaTitulo.setText("    00 : 00 : 00 : 00");
        PanelTimer.add(etiquetaTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 100, 40));

        startBtn.setText("Start");
        startBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startBtnActionPerformed(evt);
            }
        });
        PanelTimer.add(startBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelTimer, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelTimer, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void startBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startBtnActionPerformed
       t.start();
    }//GEN-LAST:event_startBtnActionPerformed
private Timer t;
private int h, m, s,cs;
private ActionListener acciones = new ActionListener() {
    
        @Override
        public void actionPerformed(ActionEvent e) {
//            throw new UnsupportedOperationException("Not supported yet."); 
        cs++;
        if(cs==100){
            cs =0;
            ++s;
        }
        if(s==60){
            s=0;
            ++m;
        }if(m==60){
            m=0;
            ++h;
        }  
        actualizarLabel();
        }
    };
private void actualizarLabel(){
String tiempo = (h<=9?"0":"")+h+":"+(m<=9?"0":"")+m+":"+(s<=9?"0":"")+s+":"+(cs<=9?"0":"")+cs;
etiquetaTitulo.setText(tiempo);
}



    @Override
    public String toString() {
        return super.toString(); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }

  

    @Override
    public boolean handleEvent(Event evt) {
        return super.handleEvent(evt); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }
    
    
    
        
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelTimer;
    private javax.swing.JLabel etiquetaTitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton startBtn;
    // End of variables declaration//GEN-END:variables
}
