/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package juegosmesa;

import juegosmesa.DamasChinas.Control;

/**
 *
 * @author Moise
 */
public class Damas extends javax.swing.JFrame {

    
    /**
     * Creates new form HanoiGame
     */
    public Damas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        C00 = new javax.swing.JButton();
        C20 = new javax.swing.JButton();
        C30 = new javax.swing.JButton();
        C40 = new javax.swing.JButton();
        C50 = new javax.swing.JButton();
        C70 = new javax.swing.JButton();
        C60 = new javax.swing.JButton();
        C10 = new javax.swing.JButton();
        C01 = new javax.swing.JButton();
        C11 = new javax.swing.JButton();
        C21 = new javax.swing.JButton();
        C31 = new javax.swing.JButton();
        C41 = new javax.swing.JButton();
        C51 = new javax.swing.JButton();
        C61 = new javax.swing.JButton();
        C71 = new javax.swing.JButton();
        C02 = new javax.swing.JButton();
        C12 = new javax.swing.JButton();
        C22 = new javax.swing.JButton();
        C32 = new javax.swing.JButton();
        C42 = new javax.swing.JButton();
        C52 = new javax.swing.JButton();
        C62 = new javax.swing.JButton();
        C72 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        C03 = new javax.swing.JButton();
        C13 = new javax.swing.JButton();
        C23 = new javax.swing.JButton();
        C33 = new javax.swing.JButton();
        C43 = new javax.swing.JButton();
        C53 = new javax.swing.JButton();
        C63 = new javax.swing.JButton();
        C73 = new javax.swing.JButton();
        C04 = new javax.swing.JButton();
        C14 = new javax.swing.JButton();
        C24 = new javax.swing.JButton();
        C34 = new javax.swing.JButton();
        C44 = new javax.swing.JButton();
        C54 = new javax.swing.JButton();
        C64 = new javax.swing.JButton();
        C74 = new javax.swing.JButton();
        C05 = new javax.swing.JButton();
        C15 = new javax.swing.JButton();
        C25 = new javax.swing.JButton();
        C35 = new javax.swing.JButton();
        C45 = new javax.swing.JButton();
        C55 = new javax.swing.JButton();
        C65 = new javax.swing.JButton();
        C75 = new javax.swing.JButton();
        C06 = new javax.swing.JButton();
        C16 = new javax.swing.JButton();
        C26 = new javax.swing.JButton();
        C36 = new javax.swing.JButton();
        C46 = new javax.swing.JButton();
        C56 = new javax.swing.JButton();
        C66 = new javax.swing.JButton();
        C76 = new javax.swing.JButton();
        C07 = new javax.swing.JButton();
        C17 = new javax.swing.JButton();
        C27 = new javax.swing.JButton();
        C37 = new javax.swing.JButton();
        C47 = new javax.swing.JButton();
        C57 = new javax.swing.JButton();
        C67 = new javax.swing.JButton();
        C77 = new javax.swing.JButton();
        cronometro1 = new juegosmesa.Cronometro();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jButton5.setText("jButton1");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        C00.setBackground(new java.awt.Color(255, 102, 102));
        C00.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegosmesa/DamasChinas/negro.png"))); // NOI18N
        C00.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        C00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C00ActionPerformed(evt);
            }
        });
        getContentPane().add(C00, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 91));

        C20.setBackground(new java.awt.Color(255, 102, 102));
        C20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegosmesa/DamasChinas/negro.png"))); // NOI18N
        C20.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(C20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 181, 110, 90));

        C30.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(C30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 110, 91));

        C40.setBackground(new java.awt.Color(255, 102, 102));
        C40.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(C40, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 110, 91));

        C50.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(C50, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 110, 91));

        C70.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(C70, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 110, 91));

        C60.setBackground(new java.awt.Color(255, 102, 102));
        C60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegosmesa/DamasChinas/rojo.png"))); // NOI18N
        C60.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(C60, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 110, 91));

        C10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        C10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C10ActionPerformed(evt);
            }
        });
        getContentPane().add(C10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 110, 91));

        C01.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        C01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C01ActionPerformed(evt);
            }
        });
        getContentPane().add(C01, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 110, 91));

        C11.setBackground(new java.awt.Color(255, 102, 102));
        C11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegosmesa/DamasChinas/negro.png"))); // NOI18N
        C11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(C11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 110, 91));

        C21.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(C21, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 110, 91));

        C31.setBackground(new java.awt.Color(255, 102, 102));
        C31.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(C31, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 110, 91));

        C41.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(C41, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 110, 91));

        C51.setBackground(new java.awt.Color(255, 102, 102));
        C51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegosmesa/DamasChinas/rojo.png"))); // NOI18N
        C51.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(C51, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 110, 91));

        C61.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(C61, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 540, 110, 91));

        C71.setBackground(new java.awt.Color(255, 102, 102));
        C71.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegosmesa/DamasChinas/rojo.png"))); // NOI18N
        C71.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        C71.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C71ActionPerformed(evt);
            }
        });
        getContentPane().add(C71, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 630, 110, 91));

        C02.setBackground(new java.awt.Color(255, 102, 102));
        C02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegosmesa/DamasChinas/negro.png"))); // NOI18N
        C02.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(C02, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 110, 91));

        C12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        C12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C12ActionPerformed(evt);
            }
        });
        getContentPane().add(C12, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 110, 91));

        C22.setBackground(new java.awt.Color(255, 102, 102));
        C22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegosmesa/DamasChinas/negro.png"))); // NOI18N
        C22.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(C22, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 110, 91));

        C32.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(C32, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 110, 91));

        C42.setBackground(new java.awt.Color(255, 102, 102));
        C42.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(C42, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 110, 91));

        C52.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(C52, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, 110, 91));

        C62.setBackground(new java.awt.Color(255, 102, 102));
        C62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegosmesa/DamasChinas/rojo.png"))); // NOI18N
        C62.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        C62.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C62ActionPerformed(evt);
            }
        });
        getContentPane().add(C62, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 540, 110, 91));

        C72.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(C72, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 630, 110, 91));

        jButton32.setText("jButton1");
        jButton32.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 110, 91));

        jButton33.setText("jButton1");
        jButton33.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 110, 91));

        jButton34.setText("jButton1");
        jButton34.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jButton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 110, 91));

        jButton35.setText("jButton1");
        jButton35.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jButton35, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 110, 91));

        jButton36.setText("jButton1");
        jButton36.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jButton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 110, 91));

        jButton37.setText("jButton1");
        jButton37.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jButton37, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 110, 91));

        jButton38.setText("jButton1");
        jButton38.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jButton38, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 540, 110, 91));

        jButton39.setText("jButton1");
        jButton39.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jButton39, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 630, 110, 91));

        C03.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(C03, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 110, 91));

        C13.setBackground(new java.awt.Color(255, 102, 102));
        C13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegosmesa/DamasChinas/negro.png"))); // NOI18N
        C13.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(C13, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 110, 91));

        C23.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(C23, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 110, 91));

        C33.setBackground(new java.awt.Color(255, 102, 102));
        C33.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        C33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C33ActionPerformed(evt);
            }
        });
        getContentPane().add(C33, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 110, 91));

        C43.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(C43, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 110, 91));

        C53.setBackground(new java.awt.Color(255, 102, 102));
        C53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegosmesa/DamasChinas/rojo.png"))); // NOI18N
        C53.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(C53, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, 110, 91));

        C63.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(C63, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 540, 110, 91));

        C73.setBackground(new java.awt.Color(255, 102, 102));
        C73.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegosmesa/DamasChinas/rojo.png"))); // NOI18N
        C73.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(C73, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 630, 110, 91));

        C04.setBackground(new java.awt.Color(255, 102, 102));
        C04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegosmesa/DamasChinas/negro.png"))); // NOI18N
        C04.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(C04, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 110, 91));

        C14.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(C14, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 110, 91));

        C24.setBackground(new java.awt.Color(255, 102, 102));
        C24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegosmesa/DamasChinas/negro.png"))); // NOI18N
        C24.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        C24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C24ActionPerformed(evt);
            }
        });
        getContentPane().add(C24, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 110, 91));

        C34.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        C34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C34ActionPerformed(evt);
            }
        });
        getContentPane().add(C34, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 110, 91));

        C44.setBackground(new java.awt.Color(255, 102, 102));
        C44.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        C44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C44ActionPerformed(evt);
            }
        });
        getContentPane().add(C44, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, 110, 91));

        C54.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(C54, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, 110, 91));

        C64.setBackground(new java.awt.Color(255, 102, 102));
        C64.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegosmesa/DamasChinas/rojo.png"))); // NOI18N
        C64.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(C64, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 540, 110, 91));

        C74.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(C74, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 630, 110, 91));

        C05.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(C05, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 110, 91));

        C15.setBackground(new java.awt.Color(255, 102, 102));
        C15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegosmesa/DamasChinas/negro.png"))); // NOI18N
        C15.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        C15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C15ActionPerformed(evt);
            }
        });
        getContentPane().add(C15, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, 110, 91));

        C25.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(C25, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, 110, 91));

        C35.setBackground(new java.awt.Color(255, 102, 102));
        C35.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        C35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C35ActionPerformed(evt);
            }
        });
        getContentPane().add(C35, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, 110, 91));

        C45.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(C45, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, 110, 91));

        C55.setBackground(new java.awt.Color(255, 102, 102));
        C55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegosmesa/DamasChinas/rojo.png"))); // NOI18N
        C55.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(C55, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 450, 110, 91));

        C65.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(C65, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 540, 110, 91));

        C75.setBackground(new java.awt.Color(255, 102, 102));
        C75.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegosmesa/DamasChinas/rojo.png"))); // NOI18N
        C75.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(C75, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 630, 110, 91));

        C06.setBackground(new java.awt.Color(255, 102, 102));
        C06.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegosmesa/DamasChinas/negro.png"))); // NOI18N
        C06.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(C06, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, 110, 91));

        C16.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(C16, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, 110, 91));

        C26.setBackground(new java.awt.Color(255, 102, 102));
        C26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegosmesa/DamasChinas/negro.png"))); // NOI18N
        C26.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(C26, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 180, 110, 91));

        C36.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(C36, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 270, 110, 91));

        C46.setBackground(new java.awt.Color(255, 102, 102));
        C46.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        C46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C46ActionPerformed(evt);
            }
        });
        getContentPane().add(C46, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 360, 110, 91));

        C56.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(C56, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 450, 110, 91));

        C66.setBackground(new java.awt.Color(255, 102, 102));
        C66.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegosmesa/DamasChinas/rojo.png"))); // NOI18N
        C66.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(C66, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 540, 110, 91));

        C76.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(C76, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 630, 110, 91));

        C07.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(C07, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 110, 91));

        C17.setBackground(new java.awt.Color(255, 102, 102));
        C17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegosmesa/DamasChinas/negro.png"))); // NOI18N
        C17.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(C17, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 90, 110, 91));

        C27.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(C27, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 180, 110, 91));

        C37.setBackground(new java.awt.Color(255, 102, 102));
        C37.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        C37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C37ActionPerformed(evt);
            }
        });
        getContentPane().add(C37, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 270, 110, 91));

        C47.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(C47, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 360, 110, 91));

        C57.setBackground(new java.awt.Color(255, 102, 102));
        C57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegosmesa/DamasChinas/rojo.png"))); // NOI18N
        C57.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(C57, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 450, 110, 91));

        C67.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(C67, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 540, 110, 91));

        C77.setBackground(new java.awt.Color(255, 102, 102));
        C77.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegosmesa/DamasChinas/rojo.png"))); // NOI18N
        C77.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        C77.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C77ActionPerformed(evt);
            }
        });
        getContentPane().add(C77, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 630, 110, 91));
        getContentPane().add(cronometro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 200, -1, -1));

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void C00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C00ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C00ActionPerformed

    private void C01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C01ActionPerformed

    private void C10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C10ActionPerformed

    private void C12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C12ActionPerformed

    private void C15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C15ActionPerformed

    private void C24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C24ActionPerformed

    private void C33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C33ActionPerformed

    private void C34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C34ActionPerformed

    private void C35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C35ActionPerformed

    private void C37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C37ActionPerformed

    private void C44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C44ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C44ActionPerformed

    private void C46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C46ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C46ActionPerformed

    private void C62ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C62ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C62ActionPerformed

    private void C71ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C71ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C71ActionPerformed

    private void C77ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C77ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C77ActionPerformed

    /**
     * @param args the command line arguments
     */
  
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Damas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Damas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Damas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Damas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Damas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton C00;
    public static javax.swing.JButton C01;
    public static javax.swing.JButton C02;
    public static javax.swing.JButton C03;
    public static javax.swing.JButton C04;
    public static javax.swing.JButton C05;
    public static javax.swing.JButton C06;
    public static javax.swing.JButton C07;
    public static javax.swing.JButton C10;
    public static javax.swing.JButton C11;
    public static javax.swing.JButton C12;
    public static javax.swing.JButton C13;
    public static javax.swing.JButton C14;
    public static javax.swing.JButton C15;
    public static javax.swing.JButton C16;
    public static javax.swing.JButton C17;
    public static javax.swing.JButton C20;
    public static javax.swing.JButton C21;
    public static javax.swing.JButton C22;
    public static javax.swing.JButton C23;
    public static javax.swing.JButton C24;
    public static javax.swing.JButton C25;
    public static javax.swing.JButton C26;
    public static javax.swing.JButton C27;
    public static javax.swing.JButton C30;
    public static javax.swing.JButton C31;
    public static javax.swing.JButton C32;
    public static javax.swing.JButton C33;
    public static javax.swing.JButton C34;
    public static javax.swing.JButton C35;
    public static javax.swing.JButton C36;
    public static javax.swing.JButton C37;
    public static javax.swing.JButton C40;
    public static javax.swing.JButton C41;
    public static javax.swing.JButton C42;
    public static javax.swing.JButton C43;
    public static javax.swing.JButton C44;
    public static javax.swing.JButton C45;
    public static javax.swing.JButton C46;
    public static javax.swing.JButton C47;
    public static javax.swing.JButton C50;
    public static javax.swing.JButton C51;
    public static javax.swing.JButton C52;
    public static javax.swing.JButton C53;
    public static javax.swing.JButton C54;
    public static javax.swing.JButton C55;
    public static javax.swing.JButton C56;
    public static javax.swing.JButton C57;
    public static javax.swing.JButton C60;
    public static javax.swing.JButton C61;
    public static javax.swing.JButton C62;
    public static javax.swing.JButton C63;
    public static javax.swing.JButton C64;
    public static javax.swing.JButton C65;
    public static javax.swing.JButton C66;
    public static javax.swing.JButton C67;
    public static javax.swing.JButton C70;
    public static javax.swing.JButton C71;
    public static javax.swing.JButton C72;
    public static javax.swing.JButton C73;
    public static javax.swing.JButton C74;
    public static javax.swing.JButton C75;
    public static javax.swing.JButton C76;
    public static javax.swing.JButton C77;
    private juegosmesa.Cronometro cronometro1;
    public static javax.swing.JButton jButton32;
    public static javax.swing.JButton jButton33;
    public static javax.swing.JButton jButton34;
    public static javax.swing.JButton jButton35;
    public static javax.swing.JButton jButton36;
    public static javax.swing.JButton jButton37;
    public static javax.swing.JButton jButton38;
    public static javax.swing.JButton jButton39;
    private javax.swing.JButton jButton5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
